#!/usr/bin/env python3
"""Generate a terminal-readable markdown view of the item-board.

The Bases board (projects/wynex-board.base) renders only in Obsidian, so an agent working
from a terminal can't read live item state — it falls back to the (now-stale) prose backlogs.
This emits projects/BOARD.md: the same item state as plain markdown, so a terminal agent (or
human) sees what's current without opening every item note. Regenerate after item changes
(update-vault does this; wire it into the sync cron for always-fresh).

Usage: python cortex_board.py --config /path/to/.cortex/config.yaml [--out projects/BOARD.md]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from cortex_common import load_config, parse_frontmatter

STAGE_ORDER = ["gate", "verifying", "building", "approved", "shaping", "shipped"]


def g(fm, k, d=""):
    v = fm.get(k, d)
    return "" if v is None else str(v).strip().strip('"')


def cell(s):
    return s.replace("|", "\\|").replace("\n", " ").strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--out", default="projects/BOARD.md")
    args = ap.parse_args()
    vault = Path(load_config(args.config)["vault_path"]).expanduser()

    items = []
    for f in sorted(vault.glob("projects/*/items/*.md")):
        fm = parse_frontmatter(f)
        if not fm or fm.get("type") != "item":
            continue
        items.append({
            "project": g(fm, "project"), "slug": f.stem, "stage": g(fm, "stage", "shaping"),
            "sprint": g(fm, "sprint"), "rank": g(fm, "rank"), "kind": g(fm, "kind"),
            "owner": g(fm, "owner"), "gate": g(fm, "gate"), "pr": g(fm, "pr"),
            "pr_state": g(fm, "pr_state"), "summary": g(fm, "summary"),
        })

    o = ["---", "type: board", "updated: generated",
         f'summary: "Terminal-readable view of {len(items)} board items, generated from projects/*/items/*.md. DO NOT EDIT — run cortex_board.py."',
         "---", "# Board — live item state (generated)", "",
         f"> Generated by `cortex_board.py` from `projects/*/items/*.md` ({len(items)} items). "
         "**Do not edit by hand** — edit the item note. Obsidian board: `projects/wynex-board.base`; this is its terminal-readable twin.", ""]

    gates = [i for i in items if i["stage"] == "gate"]
    if gates:
        o += ["## Gate — needs Wutti (STOP-2 / go decision)", "", "| Project | Item | Why |", "|---|---|---|"]
        o += [f'| {i["project"]} | [[{i["slug"]}]] | {cell(i["gate"] or i["summary"])} |'
              for i in sorted(gates, key=lambda x: (x["project"], x["slug"]))]
        o += [""]

    flight = [i for i in items if i["stage"] in ("approved", "building", "verifying")]
    if flight:
        o += ["## In flight (approved / building / verifying)", "",
              "| Project | Item | Stage | Owner | PR | Summary |", "|---|---|---|---|---|---|"]
        o += [f'| {i["project"]} | [[{i["slug"]}]] | {i["stage"]} | {i["owner"]} | {cell(i["pr"]+" "+i["pr_state"])} | {cell(i["summary"])} |'
              for i in sorted(flight, key=lambda x: (x["project"], x["slug"]))]
        o += [""]

    o += ["## By project", ""]
    for p in sorted(set(i["project"] for i in items)):
        pit = [i for i in items if i["project"] == p]

        def sk(i):
            try:
                r = int(i["rank"])
            except ValueError:
                r = 999
            return (STAGE_ORDER.index(i["stage"]) if i["stage"] in STAGE_ORDER else 9, i["sprint"], r)

        o += [f"### {p} ({len(pit)})", "", "| Stage | Sprint·rank | Kind | Item | Summary |", "|---|---|---|---|---|"]
        o += [f'| {i["stage"]} | {cell(i["sprint"])}·{i["rank"]} | {i["kind"]} | [[{i["slug"]}]] | {cell(i["summary"])} |'
              for i in sorted(pit, key=sk)]
        o += [""]

    (vault / args.out).write_text("\n".join(o) + "\n")
    print(f"wrote {args.out}: {len(items)} items across {len(set(i['project'] for i in items))} projects")


if __name__ == "__main__":
    main()
